---
include:
- "**/*.rb"
- "**/*.haml"
exclude:
- node_modules/**/*
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
reporters:
- rubocop:version=0.81.0  # diagnostics
formatter:
  rubocop:
    version: 0.61.0
require_paths: []
plugins: []
max_files: 5000
