addons:
  postgresql: 11.8
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database oscar_web_test;' -U postgres
  - sleep 15
  - mongo oscar_web_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
before_install:
  - gem install bundler -v '1.17.3'
dist: trusty
language: ruby
rvm:
  - 2.3.3
script:
  - bundle exec rails db:schema:load RAILS_ENV=test
  - bundle exec rspec spec/models
services:
  - redis-server
  - mongodb
env:
  global:
    - PGPORT=5432
    - DATABASE_NAME_TEST=oscar_web_test
    - DATABASE_USER=postgres
    - DATABASE_HOST=localhost
    - HISTORY_DATABASE_HOST=localhost
    - HISTORY_DATABASE_NAME=oscar-history_test
    - CASE_WORKER_CLIENT_OFFLINE_DATABASE=case_worker_client_offline_test
notifications:
  email:
    recipients:
      - darren.jensen@devzep.com
      - damon.hase@devzep.com
      - kiry.meas@devzep.com
      - makara.pao@devzep.com
    on_success: never
    on_failure: always
