language: ruby
dist: trusty
rvm:
  - 2.3.3
cache:
  - bundler
  - yarn
addons:
  postgresql: 11.8
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11
before_script:
  - psql -c 'CREATE DATABASE IF NOT EXISTS oscar_web_test;' -U postgres
  - sleep 15
  - mongo oscar_web_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
before_install:
  - nvm install --lts
  - gem install bundler -v '1.17.3'
  - sudo /etc/init.d/postgresql stop
script:
  - bundle exec rspec spec/models
services:
  - postgresql
  - redis-server
  - mongodb
env:
  global:
    - PGPORT=5432
    - DATABASE_NAME_TEST=oscar_web_test
    - DATABASE_USER=postgres
    - DATABASE_HOST=localhost
    - HISTORY_DATABASE_HOST=localhost
    - HISTORY_DATABASE_NAME=oscar-history_test
    - CASE_WORKER_CLIENT_OFFLINE_DATABASE=case_worker_client_offline_test
notifications:
  email:
    recipients:
      - darren.jensen@devzep.com
      - damon.hase@devzep.com
      - kiry.meas@devzep.com
      - makara.pao@devzep.com
    on_success: never
    on_failure: always
