source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'
# gem 'rails',                  '4.2.2'
gem 'rails',                  '~> 5.2', '<= 5.2.4.4'
gem 'pg',                     '~> 0.18.4'
gem 'puma',                   '~> 3.11'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'sass-rails',             '~> 6.0'
gem 'uglifier',               '~> 4.2'
gem 'coffee-rails',           '~> 5.0'
gem 'bootsnap',               '>= 1.1.0', require: false
gem 'mini_racer',             '~> 0.6.3', platforms: :ruby
gem 'jbuilder',               '~> 2.10', '>= 2.10.1'
gem 'simple_form',            '~> 5.0', '>= 5.0.3'
gem 'bootstrap-sass',         '~> 3.4', '>= 3.4.1'
gem 'devise',                 '~> 4.7', '>= 4.7.3'
gem 'haml-rails',             '~> 2.0', '>= 2.0.1'
gem 'dotenv-rails',           '~> 2.7', '>= 2.7.6'
gem 'roo',                    '~> 2.8', '>= 2.8.3'
gem 'fog-aws',                '~> 3.3'
gem 's3'
gem 'ffaker',                 '~> 2.17'
gem 'draper',                 '~> 4.0', '>= 4.0.1'
gem 'datagrid',               '~> 1.6', '>= 1.6.1'
gem 'active_model_serializers'
gem 'sinatra',                require: false
gem 'rack-cors',              require: 'rack/cors'
gem 'rails-erd'
gem 'phony_rails',            '~> 0.14.13'
gem 'typhoeus'
gem 'foreman',                '~> 0.87.2'
gem 'cancancan',              '~> 3.1'
gem 'pundit',                 '~> 2.1'
gem 'tinymce-rails',          '~> 5.6', '>= 5.6.2.1'
gem 'bootstrap-datepicker-rails', '~> 1.9', '>= 1.9.0.1'
gem 'x-editable-rails',       '~> 1.5', '>= 1.5.5.1'
gem 'select2-rails',          '~> 4.0', '>= 4.0.13'
gem 'doorkeeper',             '~> 5.4'
gem 'devise_token_auth'
gem 'omniauth',               '~> 1.9', '>= 1.9.1'
gem 'jquery-validation-rails'
gem 'google-api-client',      '~> 0.23.9', require: 'google/apis/calendar_v3'
gem 'google_calendar',        '~> 0.6.4'
gem 'fullcalendar-rails',     '~> 3.9'
gem 'momentjs-rails',         '~> 2.20', '>= 2.20.1'
gem 'kaminari'
gem 'jquery-datatables-rails', '~> 3.4'
gem 'friendly_id',            '~> 5.4', '>= 5.4.1'
gem 'wicked_pdf',             '~> 2.1'
gem 'wkhtmltopdf-binary-edge', '~> 0.12.6.0'
gem 'browser',                '~> 5.1'
gem 'whenever',               '~> 1.0'
gem 'thredded',               '~> 0.16.4'
gem 'cocoon',                 '~> 1.2', '>= 1.2.15'
gem 'paper_trail',            '~> 10.0', '>= 10.0.1'
gem 'paper_trail-association_tracking', '~> 2.1', '>= 2.1.1'
gem 'carrierwave',            '~> 2.1'
gem 'mini_magick',            '~> 4.11'
gem 'chartkick',              '~> 3.4', '>= 3.4.2'
gem 'font-awesome-rails',     '~> 4.7', '>= 4.7.0.5'
gem 'spreadsheet',            '~> 1.2', '>= 1.2.6'
gem 'apartment',              '~> 2.2', '>= 2.2.1'
gem 'dropzonejs-rails',       '~> 0.8.5'
gem 'bourbon',                '~> 7.0'
gem 'neat',                   '~> 1.7', '>= 1.7.4'
gem 'sidekiq',                '~> 5.2', '>= 5.2.9'
gem 'mongoid',                '~> 6.1', '>= 6.1.1'
gem 'dotiw',                  '~> 5.2'
gem 'text',                   '~> 1.3', '>= 1.3.1'
gem 'acts_as_paranoid',       '~> 0.7.0'
gem 'ancestry',               '~> 3.2', '>= 3.2.1'
gem 'sysrandom',              '~> 1.0', '>= 1.0.5'
gem 'write_xlsx',             '~> 0.86.0'
gem 'caxlsx',                 '~> 3.0', '>= 3.0.3'
gem 'react-rails',            '~> 2.6', '>= 2.6.1'
gem 'webpacker',              '~> 5.2', '>= 5.2.1'
gem 'jquery_query_builder-rails', '~> 0.5.0'
gem 'globalize',              '~> 5.3'
gem 'enumerize',              '~> 2.3', '>= 2.3.1'
gem 'ulid',                   '~> 1.2'
gem 'dalli',                  '~> 2.7', '>= 2.7.11'
gem 'aws-healthcheck'
gem 'redis-session-store',    '~> 0.11.3'
gem 'actionpack-page_caching', '~> 1.2', '>= 1.2.3'
gem 'actionpack-action_caching', '~> 1.2', '>= 1.2.1'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'rspec-rails'
  gem 'factory_girl_rails',   '~> 4.9'
  gem 'launchy',              '~> 2.4', '>= 2.4.3'
  gem 'capybara',             '~> 2.15.4'
  gem 'poltergeist',          '~> 1.9.0'
  gem 'phantomjs'
  gem 'shoulda-whenever',     '~> 0.0.2'
  gem 'bullet',               '~> 6.1'
  gem 'mongoid-rspec', '~> 4.0', '>= 4.0.1'
  gem 'thin',                 '~> 1.7'
  gem 'danger',               '~> 5.16', '>= 5.16.1'
  gem 'sorbet-rails'
end

group :staging, :ratanak_staging, :demo, :production do
  gem 'appsignal', '~> 3.0', '>= 3.0.24'
  gem 'asset_sync'
end

group :staging, :demo do
  gem 'mail_interceptor', '~> 0.0.7'
end

group :development do
  gem 'letter_opener',        '~> 1.4.1'
  gem 'letter_opener_web'
  gem 'rubocop',              '~> 0.81.0', require: false
  gem 'capistrano',           '3.9.0'
  gem 'capistrano-rails',     '~> 1.1.1'
  gem 'capistrano-passenger', '~> 0.1.1'
  gem 'capistrano-rvm',       '~> 0.1.2'
  gem 'capistrano-sidekiq',   '~> 1.0', '>= 1.0.3'
  gem 'capistrano-foreman'
  gem 'rack-mini-profiler',   '~> 1.0'
  gem 'metainspector'
  gem 'flay',                 '~> 2.12', '>= 2.12.1'
  gem 'active_record_doctor', '~> 1.8'
  gem 'lol_dba',              '~> 2.2'
end

group :test do
  gem 'database_cleaner',     '~> 1.5', '>= 1.5.1'
  gem 'json_spec',            '~> 1.1', '>= 1.1.5'
  gem 'shoulda-matchers'
  gem 'rspec-sidekiq',        '~> 3.0', '>= 3.0.3'
  gem 'rspec-activemodel-mocks', '~> 1.1'
  gem 'timecop',              '~> 0.8.1'
end

gem "sentry-raven", "~> 2.13"
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
