source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.6'

gem 'rails',                    '~> 5.2', '<= 5.2.8.1'
gem 'pg',                       '~> 1.4', '>= 1.4.4'
gem 'puma',                     '~> 6.0'
gem 'jquery-rails',             '~> 4.5'
gem 'jquery-ui-rails',          '~> 6.0', '>= 6.0.1'
gem 'sass-rails',               '~> 5.0'
gem 'terser',                   '~> 1.1', '>= 1.1.12'
gem 'coffee-rails',             '~> 5.0'
gem 'bootsnap',                 '~> 1.13', require: false
gem 'mini_racer',               '~> 0.6.3', platforms: :ruby
gem 'jbuilder',                 '~> 2.11', '>= 2.11.5'
gem 'simple_form',              '~> 5.1'
gem 'bootstrap-sass',           '~> 3.4', '>= 3.4.1'
gem 'devise',                   '~> 4.8', '>= 4.8.1'
gem 'haml-rails',               '~> 2.1'
gem 'dotenv-rails',             '~> 2.8', '>= 2.8.1'
gem 'roo',                      '~> 2.9'
gem 'fog-aws',                  '~> 3.15'
gem 's3',                       '~> 0.3.29'
gem 'ffaker',                   '~> 2.21'
gem 'draper',                   '~> 4.0', '>= 4.0.2'
gem 'datagrid',                 '~> 1.6', '>= 1.6.3'
gem 'active_model_serializers', '~> 0.10.13'
gem 'sinatra',                  '~> 3.0', '>= 3.0.2',  require: false
gem 'rack-cors',                '~> 1.1', '>= 1.1.1', require: 'rack/cors'
gem 'rails-erd',                '~> 1.7', '>= 1.7.2'
gem 'phony_rails',              '~> 0.15.0'
gem 'typhoeus',                 '~> 1.4'
gem 'foreman',                  '~> 0.87.2'
gem 'cancancan',                '~> 3.4'
gem 'pundit',                   '~> 2.2'
gem 'tinymce-rails',            '~> 6.2'
gem 'bootstrap-datepicker-rails', '~> 1.9', '>= 1.9.0.1'
gem 'x-editable-rails',         '~> 1.5', '>= 1.5.5.1'
gem 'select2-rails',            '~> 4.0', '>= 4.0.13'
gem 'doorkeeper',               '~> 5.6'
gem 'devise_token_auth',        '~> 1.2', '>= 1.2.1'
gem 'omniauth',                 '~> 2.1'
gem 'jquery-validation-rails',  '~> 1.19'
gem 'google-api-client',        '~> 0.53.0', require: 'google/apis/calendar_v3'
gem 'google_calendar',          '~> 0.6.4'
gem 'fullcalendar-rails',       '~> 3.9'
gem 'momentjs-rails',           '~> 2.29', '>= 2.29.4.1'
gem 'kaminari',                 '~> 1.2', '>= 1.2.2'
gem 'jquery-datatables-rails',  '~> 3.4'
gem 'friendly_id',              '~> 5.4', '>= 5.4.2'
gem 'wicked_pdf',               '~> 2.6', '>= 2.6.3'
gem 'wkhtmltopdf-binary-edge',  '~> 0.12.6.0'
gem 'browser',                  '~> 5.3', '>= 5.3.1'
gem 'whenever',                 '~> 1.0'
gem 'thredded',                 '~> 1.0', '>= 1.0.1'
gem 'cocoon',                   '~> 1.2', '>= 1.2.15'
gem 'paper_trail',              '~> 13.0'
gem 'paper_trail-association_tracking', '~> 2.2', '>= 2.2.1'
gem 'carrierwave',              '~> 2.2'
gem 'mini_magick',              '~> 4.11'
gem 'chartkick',                '~> 4.2', '>= 4.2.1'
gem 'font-awesome-rails',       '~> 4.7', '>= 4.7.0.8'
gem 'spreadsheet',              '~> 1.3'
gem 'apartment',                '~> 2.2', '>= 2.2.1'
gem 'dropzonejs-rails',         '~> 0.8.5'
gem 'bourbon',                  '~> 6.0'
gem 'neat',                     '~> 4.0'
gem 'sidekiq',                  '~> 6.5', '>= 6.5.7'
gem 'mongoid',                  '~> 6.4.8'
gem 'dotiw',                    '~> 5.3', '>= 5.3.3'
gem 'text',                     '~> 1.3', '>= 1.3.1'
gem 'acts_as_paranoid',         '~> 0.8.1'
gem 'ancestry',                 '~> 3.2', '>= 3.2.1'
gem 'sysrandom',                '~> 1.0', '>= 1.0.5'
gem 'write_xlsx',               '~> 1.9', '>= 1.09.4'
gem 'caxlsx',                   '~> 3.0', '>= 3.0.4'
gem 'react-rails',              '~> 2.6', '>= 2.6.2'
gem 'webpacker',                '~> 5.4', '>= 5.4.3'
gem 'jquery_query_builder-rails', '~> 0.5.0'
gem 'globalize',                '~> 6.2', '>= 6.2.1'
gem 'enumerize',                '~> 2.5'
gem 'ulid',                     '~> 1.3'
gem 'dalli',                    '~> 3.2', '>= 3.2.2'
gem 'aws-healthcheck',          '~> 2.0'
gem 'redis-session-store',      '~> 0.11.4'
gem 'actionpack-page_caching',  '~> 1.2', '>= 1.2.4'
gem 'actionpack-action_caching', '~> 1.2', '>= 1.2.2'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry',                    '~> 0.14.1'
  gem 'rspec-rails',            '~> 5.1', '>= 5.1.2'
  gem 'factory_bot_rails',      '~> 6.2'
  gem 'launchy',                '~> 2.5'
  gem 'capybara',               '~> 3.37', '>= 3.37.1'
  gem 'poltergeist',            '~> 1.18', '>= 1.18.1'
  gem 'phantomjs',              '~> 2.1', '>= 2.1.1.0'
  gem 'shoulda-whenever',       '~> 0.0.2'
  gem 'bullet',                 '~> 7.0', '>= 7.0.3'
  gem 'mongoid-rspec',          '~> 4.1'
  gem 'thin',                   '~> 1.8', '>= 1.8.1'
  gem 'sorbet-rails',           '~> 0.7.34'
end

group :staging, :ratanak_staging, :demo, :production do
  gem 'appsignal',                '~> 3.1', '>= 3.1.5'
  gem 'asset_sync',               '~> 2.16'
end

group :staging, :demo do
  gem 'mail_interceptor',         '~> 0.0.7'
end

group :development do
  gem 'web-console',              '>= 3.3.0'
  gem 'listen',                   '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen',    '~> 2.0.0'

  gem 'letter_opener',            '~> 1.8', '>= 1.8.1'
  gem 'letter_opener_web',        '~> 2.0'
  gem 'rubocop',                  '~> 1.37', '>= 1.37.1', require: false
  gem 'capistrano',               '~> 3.17', '>= 3.17.1'
  gem 'capistrano-rails',         '~> 1.6', '>= 1.6.2'
  gem 'capistrano-passenger',     '~> 0.2.1'
  gem 'capistrano-rvm',           '~> 0.1.2'
  gem 'capistrano-sidekiq',       '~> 2.3'
  gem 'capistrano-foreman',       '~> 1.4'
  gem 'rack-mini-profiler',       '~> 3.0'
  gem 'metainspector',            '~> 5.13'
  gem 'flay',                     '~> 2.13'
  gem 'active_record_doctor',     '~> 1.10'
  gem 'lol_dba',                  '~> 2.4'
end

group :test do
  gem 'database_cleaner',         '~> 2.0', '>= 2.0.1'
  gem 'json_spec',                '~> 1.1', '>= 1.1.5'
  gem 'shoulda-matchers',         '~> 5.2'
  gem 'rspec-sidekiq',            '~> 3.1'
  gem 'rspec-activemodel-mocks',  '~> 1.1'
  gem 'rails-controller-testing', '~> 1.0', '>= 1.0.5'
  gem 'timecop',                  '~> 0.9.5'
end

gem 'sentry-raven',               '~> 3.1', '>= 3.1.2'
gem 'tzinfo-data', '~> 1.2022', '>= 1.2022.6', platforms: %i[mingw mswin x64_mingw jruby]
