---

- name: Internal | Create k8s deploy directory
  file:
    path: '{{ workspace }}/k8s-deploy'
    state: directory
    mode: 0755

- name: Copy deployment files
  template:
    src: '{{ item }}'
    dest: '{{ workspace }}/k8s-deploy/{{ item | basename | regex_replace("\.j2$", "") }}'
  with_fileglob:
    '../templates/*.j2'

- name: K8s apply namespace and databases
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/{{ item }}'
  loop:
    - namespace.yml
    - pvc.yml
    - redis.yml
    - postgres.yml
    - mongo.yml

- name: K8s apply po and ing
  shell: 'KUBECONFIG={{ kubeconfig }} kubectl apply -f {{ workspace }}/k8s-deploy/{{ item }} --wait=true'
  loop:
    - webapp.yml
    - webpack.yml
    - sidekiq.yml
    - ingress.yml

- name: Wait until container ready
  shell: |
    while [[ $(KUBECONFIG={{ kubeconfig }} kubectl -n {{ k8s_namespace }} get po -l app=app-{{ stage }}-{{ project_id }}-webapp -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]] ; do echo "waiting for pod" && sleep 1 ; done
  args:
    executable: /bin/bash
