---

- name: Run bundle install
  shell: bundle install --verbose --jobs 20 --retry 5
  args:
    chdir: '{{ workspace }}'

- name: Run yarn install
  shell: yarn install
  args:
    chdir: '{{ workspace }}'

- name: Deploy to production server
  shell: cap production deploy
  args:
    chdir: '{{ workspace }}'
